development:
  inventario:
    identifier: '761e2621'
    secret: '8740dbce820d968fe4c98a15cf1dd309'
  ventas:
    identifier: 'i39x9mq1'
    secret: '1340dbce820ds68fe4c9xa15cf1dd3wp'
test:
production:
